
import Head from 'next/head';
import { useRouter } from 'next/router'
import ReactMarkdown from 'react-markdown'
import styles from '../../styles/Home.module.css'


function Post() {
    // Get [id] param from router.
    const router = useRouter()
    const id = router.query.id

    // Only load if id is available.
    if (!id) {
        return <div>
            <Head>
                <title>123 - blog of liamz</title>
            </Head>
        </div>
    }

    // Load post from file
    // ../posts/${id}.md
    const fileContent = require(`../../posts/${id}.md.json`)

    return  <div className={styles.container}>
      <Head>
        <title>blog of liamz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <header className={styles.header}></header>

      <main className={styles.main}>
            <a href="../">{"<< back to posts"}</a>
            <article className={styles.article}>
                <ReactMarkdown components={{
                    // open new tab <a href="" target="_blank">
                    img: ({ node, ...props }) => <a href={props.src} target="_blank"><img {...props} style={{ maxWidth: '100%' }} /></a>
                }}>
                    {fileContent.content}
                </ReactMarkdown>
            </article>
      </main>

    </div>

}

export default Post;