import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Md } from '../components/md'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>consulting - blog of liamz</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.header}></header>

            <main className={styles.main}>

                <h1>my work</h1>

                <p><strong>Liam Zebedee</strong> &middot; founder/consultant</p>

                <p><strong>Who am I</strong>? {`I'm`} an independent consultant and researcher, specialising in crypto, product design and the forefront of new technology (zero knowledge proofs, blockchains, generative AI).</p>

                <Md>
                    {`
**Hard skills**:
* **Frontend**. React, JS, Next.js.
* **Backend**. Any, mostly JS/TS, Go, Python. 
* **Systems**. Bash, Docker, Python, Unix.
* **Software architecture**. Monorepos, software design [[1]](http://www.jwz.org/doc/worse-is-better.html), good modularity.
* **Data science**. IPython/Jupyter, Matplotlib, Numpy.
* **Smart contracts**. Solidity, Foundry, Cairo, Tendermint/Cosmos.
* **Cryptography**. ZK proofs, ZK circuits, SNARKs, STARKs, MPC, homomorphic encryption.
* **Protocol engineering**. libp2p. Cross-chain architecture & state transfer.
* **Cryptoeconomics**. Token design, game theory, incentives, simulation.
* **Distributed systems**. Consensus, databases, RPC, networking, DHT's.

**Soft skills**:
* **Design**. Typography, colour theory, UI, UX, user interviews, prototyping at various fidelities (wireframes, Figma).
* **Writing**. 
* **Product**.
* **Branding and storytelling**. Creating a good meme, brand, and narrative.
* **Innovation**.

**Unique capabilities**:
* **Obsessive learner**. In 2022, I wanted to build a social network. I went from knowing 0 about ZK STARK's to becoming an expert on the technology, in around 6mo.
* **A wordcel and a shape rotator**.

**Experience**:

I've done work with Ethereum Foundation, Keep Network, Synthetix, [Chainflip](https://chainflip.io/), Herodotus.

* **Founder**. In Q4 2022, I launched 3 products - [Mergeswap](https://twitter.com/0xmarcello/status/1569947688208330752), [Dappnet](https://twitter.com/liamzebedee/status/1578127982173908992), and [Take](https://twitter.com/takeisxx). Dappnet went viral, and I was featured in The Block, The Daily Gwei, and raised $50k from the NFT sale. 
* **Engineer**. I've developed smart contracts which have processed over $500M of value, such as Synthetix's [EtherWrapper](https://github.com/Synthetixio/synthetix/pull/1178) and the core contracts of [tBTC v1](https://github.com/keep-network/tbtc). I helped with Synthetix's [simulated liquidity](https://twitter.com/liamzebedee/status/1437240069870415872) in SIP-181.
* **Pioneering**. In 2019, [we built the first-ever ZKDAO POC at ETHBerlin II](http://localhost/blog/building-the-first-ever-zkdao-at-ethparis/). 

**Niche things**:
* I enjoy Lisp, functional programming, mathematics.
`}
                </Md>


            </main>

        </div>
    )
}


