import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>blog of liamz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}></header>

      <main className={styles.main}>
        <h2>Posts</h2>
        <p className={styles.description}>
          <Link href="/posts/how-i-found-my-new-house-thru-6-degrees">How I found my new house through 6 degrees of separation.</Link>
        </p>
        
      </main>

    </div>
  )
}
