import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>blog of liamz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}></header>

      <main className={styles.main}>

        <h1>blog of liamz</h1>

        {/* <h2>ZK</h2>
        <p className={styles.description}>
          <ul>
            <li>
              <Link href="/posts/anatomy-of-a-stark-proof">
                Anatomy of a STARK proof
              </Link>
            </li>
            <li>
              <Link href="/posts/dumb-primer-on-recursive-zk-proofs">
                A dumb primer on recursive ZK proofs
              </Link>
            </li>
            <li>
              <Link href="/posts/loot-fog-of-war-private-information-zk">
                Loot Fog of War, private-information games, and ZK STARK's.
              </Link>
            </li>
          </ul>
        </p> */}
        <p>
          Welcome to my new blog. You can find my old one <a href="https://liamz.co/blog/">here</a>.
        </p>
        <p>
          <a href="https://twitter.com/liamzebedee">Twitter</a>
        </p>



        <strong>Writing</strong>
        <p className={styles.description}>
          <Link href="/posts/how-i-found-my-new-house-thru-6-degrees">How I found my new house through 6 degrees of separation.</Link>
        </p>
        
      </main>

    </div>
  )
}
